# Generated by Django 5.0 on 2025-04-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UmrahPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nama Paket")),
                ("description", models.TextField(verbose_name="Deskripsi Paket")),
                (
                    "facilities",
                    models.TextField(verbose_name="Fasilitas yang Diperoleh"),
                ),
                (
                    "departure_date",
                    models.DateField(verbose_name="Jadwal Keberangkatan"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Harga"
                    ),
                ),
                (
                    "package_image",
                    models.ImageField(
                        upload_to="package_images/", verbose_name="Foto Stiker Paket"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Paket Umroh",
                "verbose_name_plural": "Paket Umroh",
                "ordering": ["-departure_date"],
            },
        ),
    ]
