# Generated by Django 5.0 on 2025-04-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="umrahpackage",
            name="facilities",
            field=models.TextField(
                help_text="Masukkan satu fasilitas per baris",
                verbose_name="Fasilitas yang Diperoleh",
            ),
        ),
        migrations.AlterField(
            model_name="umrahpackage",
            name="package_image",
            field=models.ImageField(
                help_text="Unggah gambar dengan rasio 21:30 untuk hasil terbaik",
                upload_to="package_images/",
                verbose_name="Foto Stiker Paket",
            ),
        ),
    ]
