# Generated by Django 5.0 on 2025-04-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_umrahpackage_facilities_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="umrahpackage",
            name="duration",
            field=models.PositiveIntegerField(default=10, verbose_name="Durasi (hari)"),
        ),
        migrations.AddField(
            model_name="umrahpackage",
            name="poster_filename",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Nama File Poster"
            ),
        ),
        migrations.AddField(
            model_name="umrahpackage",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
