# Generated by Django 5.2 on 2025-04-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_umrahpackage_duration_umrahpackage_poster_filename_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="umrahpackage",
            name="is_promo",
            field=models.BooleanField(default=False, verbose_name="Promo Aktif"),
        ),
        migrations.AddField(
            model_name="umrahpackage",
            name="promo_end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Tanggal Berakhir Promo"
            ),
        ),
        migrations.AddField(
            model_name="umrahpackage",
            name="promo_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Harga Promo",
            ),
        ),
    ]
